version: '3'

services:
  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123
  #   ports:
  #     - "3306:3306"

  node:
    build: .
    ports:
     - "3001:3001"
     - "3000:3000"
    # depends_on:
    #   - db
    # environment:
    #   DB_HOST: 172.18.0.2
    #   DB_USER: root
    #   DB_PASSWORD: 123