version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bdcarona
    volumes:
      - ./carona.sql:/docker-entrypoint-initdb.d/carona.sql

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: bdcarona